name: Advanced1vs1
main: jkorn\ad1vs1\AD1vs1Main
version: 1.0.3
api: 2.0.0
author: jkorn
description: An advanced 1vs1 plugin that uses other kit plugins.
website: https://github.com/jkorn2324

permissions:
  permission.ad1vs1.duel:
    default: true
    description: Permission to queue to a duel.
  permission.ad1vs1.manage.arenas:
    default: op
    description: Permission to create, delete, edit arenas.
  permission.ad1vs1.listarenas:
    default: op
    description: Permission to view the list of arenas.